---
apiVersion: v1
kind: Namespace
metadata:
  name: dns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempdns
  namespace: dns
  labels:
    labs.doubleu.codes/instance: tempdns
    labs.doubleu.codes/name: tempdns
spec:
  replicas: 1
  selector:
    matchLabels:
      labs.doubleu.codes/name: tempdns
      labs.doubleu.codes/instance: tempdns
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        labs.doubleu.codes/instance: tempdns
        labs.doubleu.codes/name: tempdns
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        - "-conf"
        - "/etc/coredns/Coredns"
        image: rancher/mirrored-coredns-coredns:1.10.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: tempdns
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 9153
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 170Mi
            ephemeral-storage: 1Gi
          requests:
            cpu: 100m
            memory: 70Mi
            ephemeral-storage: 250Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          readOnlyRootFileSystem: true
        volumeMounts:
        - mountPath: /etc/coredns
          name: config-volume
          readOnly: true
      dnsPolicy: Default
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: Corefile
            path: Corefile
          name: tempdns
        name: config-volume
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempdns
  namespace: dns
data:
  Corefile: |
    .:53 {
      errors
      health
      ready
      cache 30
      reload
      forward . tls://9.9.9.9 tls://149.112.112.112 {
        tls_servername dns.quad9.net
        health_check 5s
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: tempdns
  namespace: dns
spec:
  type: LoadBalancer
  selector:
    labs.doubleu.codes/instance: tempdns
    labs.doubleu.codes/name: tempdns
    metallb.universe.tf/address-pool: dns
    metallb.universe.tf/ip-allocated-from-pool: dns
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
